# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md

- name: add static route for pod
  hosts: worker:controller
  gather_facts: yes
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: add static route to interface file
      blockinfile:
        block: "{{ lookup('template', 'static_route.j2') }}"
        dest: /etc/netplan/01-netcfg.yaml
        marker: "# {mark} ANSIBLE MANAGED BLOCK add route "
        insertafter: "{{ controller_interface }}"

    - name: run netplan apply to activate route
      shell: netplan apply

    # step to propagate /etc/hosts for internal network
    - name: add /etc/hosts alias
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item.name }}.*$'
        line: "{{ item.private_ip }} {{ item.name }}"
        state: present
      with_items:
        - "{{ worker_instances }}"
        - "{{ controller_instances }}"
